[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NETLIFY_USE_CACHE = "false"
  CI = "true"

[[plugins]]
  package = "./plugins/netlify-plugin-clear-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self' https://identity.netlify.com"
