[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NETLIFY_USE_CACHE = "false"
  CI = "true"

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self' https://identity.netlify.com"
