backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "hero"
    label: "Hero Section"
    files:
      - label: "Hero Content"
        name: "hero"
        file: "src/content/hero/main.md"
        fields:
          - {label: "Title", name: "title", widget: "text"}
          - {label: "Vimeo URL", name: "vimeo", widget: "string"}
          - {label: "Is Active", name: "isActive", widget: "boolean", default: true}
          - {label: "Publish Date", name: "publishDate", widget: "datetime"}
          - {label: "Tags", name: "tag", widget: "list", required: false}
          - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
          - {label: "Description", name: "description", widget: "text", required: false}

  
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
