backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "hero"
    label: "Hero Section"
    files:
      - label: "Hero Content"
        name: "hero"
        file: "src/content/hero/main.md"
        fields:
          - {label: "Title", name: "title", widget: "text"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Vimeo URL", name: "vimeo", widget: "string"}
          - {label: "Tags", name: "tag", widget: "list", required: false}
          - {label: "Publish Date", name: "publishDate", widget: "datetime"}

  - name: "about"
    label: "About Page"
    files:
      - label: "About Content"
        name: "about"
        file: "src/content/about/main.md"
        fields:
          - {label: "Title", name: "title", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Tags", name: "tags", widget: "list", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Publish Date", name: "publishDate", widget: "datetime"}

  - name: "latest"
    label: "Latest"
    folder: "src/content/latest"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
